server:
  port: 8083

auth:
  service:
    url: http://localhost:8081
member:
  service:
    url: http://localhost:8082
jwt:
  secret: my-super-secret-key-minimum-32-bytes!!!
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
